<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to your journal!</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

<template id="entriesTemplate">
  <h2>Dina tidigare inlägg:</h2>
  <div id="entries"></div>
</template>


<template id="createNewEntryTemplate">
  <h2>Write a new post</h2>
  <form id="newEntryForm">
    <label for="title">Titel</label>
    <input type="text" name="title" id="title"> <br>
    <label for="content">Posts</label>
    <input type="textarea" name="content" id="content"> <br>
    <input type="textarea" name="userID" id="userID" value=7> <br>
    <button type="submit">Register post</button>
    
  </form>
  
</template>



<div class="container">
  <header>
    <h1> <?= $title ?> </h1>
  </header>
</div>

<main>
</main>


<script type="text/javascript" src="loggedin.js"></script>
</body>
</html>