<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>All users</title>
    <link rel="stylesheet" type="text/css" href="style.css">

</head>
<body>

<template id="allUsers">
  <h2>Here you can see everyone that uses the journal</h2>
  <div id="users"></div>

</template>
    
<main>
    
</main>

<script type="text/javascript" src="allUsers.js"></script>
</body>
</html>